export const SOCIAL_MEDIA_TYPES:Record<string, string> = {
    facebook          : 'assets/socialmedia/icons8-facebook-48.png',
    facebook_messenger: 'assets/socialmedia/icons8-facebook-messenger-48.png',
    instagram         : 'assets/socialmedia/icons8-instagram-48.png',
    pinterest         : 'assets/socialmedia/icons8-pinterest-48.png',
    reddit            : 'assets/socialmedia/icons8-reddit-48.png',
    stack_overflow    : 'assets/socialmedia/icons8-stack-overflow-48.png',
    telegram          : 'assets/socialmedia/icons8-telegram-app-48.png',
    tiktok            : 'assets/socialmedia/icons8-tiktok-48.png',
    twitter           : 'assets/socialmedia/icons8-twitter-48.png',
    linkedin          : 'assets/socialmedia/icons8-linkedin-48.png',
    wechat            : 'assets/socialmedia/icons8-wechat-48.png',
    whatsapp          : 'assets/socialmedia/icons8-whatsapp-48.png',
    xing              : 'assets/socialmedia/icons8-xing-48.png',
    youtube           : 'assets/socialmedia/icons8-youtube-48.png',
    x                 : 'assets/socialmedia/icons8-x-48.png',
}